service:
  name: project-management-api

# serverless-webpack and serverless-offline plugins
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# also enable autopacking of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  authorizer:
    main:
      name: authorize-user
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)
    default:
      name: authorize-default
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"
    - Effect: Allow
      Action:
        - congito-identity:*
        - cognito-idp:*
        - cognito-sync:*
        - iam:*
      Resource: "*"

# API endpoints for the functions
functions:
  authorize-user:
    handler: authorizer-projects.main
  authorize-default:
    handler: authorizer-default.main
  create:
    handler: create.main
    events:
      - http:
          method: post
          path: projects
          cors: true
          authorizer: ${self:custom.authorizer.default}
  get:
    handler: get.main
    events:
      - http:
          method: get
          path: projects/{id}
          cors: true
          authorizer: ${self:custom.authorizer.default}
  list:
    handler: list-projects.main
    events:
      - http:
          method: get
          path: projects
          cors: true
          authorizer: ${self:custom.authorizer.default}
  delete:
    handler: delete.main
    events:
      - http:
          method: delete
          path: projects/{id}
          cors: true
          authorizer: ${self:custom.authorizer.main}
  modify:
    handler: modify.main
    events:
      - http:
          method: put
          path: projects/{id}
          cors: true
          authorizer: ${self:custom.authorizer.main}
  create-role:
    handler: create-role.main
    events:
      - http:
          method: post
          path: projects/{id}/roles
          cors: true
          authorizer: ${self:custom.authorizer.main}
  delete-role:
    handler: delete-role.main
    events:
      - http:
          method: delete
          path: projects/{id}/roles
          cors: true
          authorizer: ${self:custom.authorizer.main}
  modify-role:
    handler: modify-role.main
    events:
      - http:
          method: put
          path: projects/{id}/roles
          cors: true
          authorizer: ${self:custom.authorizer.main}
  create-group:
    handler: create-group.main
    events:
      - http:
          method: post
          path: projects/{id}/groups
          cors: true
          authorizer: ${self:custom.authorizer.main}
  delete-group:
    handler: delete-group.main
    events:
      - http:
          method: delete
          path: projects/{id}/groups
          cors: true
          authorizer: ${self:custom.authorizer.main}
  modify-group:
    handler: modify-group.main
    events:
      - http:
          method: put
          path: projects/{id}/groups
          cors: true
          authorizer: ${self:custom.authorizer.main}
  add-user:
    handler: add-user.main
    events:
      - http:
          method: post
          path: projects/{id}/users
          cors: true
          authorizer: ${self:custom.authorizer.main}
  remove-user:
    handler: remove-user.main
    events:
      - http:
          method: delete
          path: projects/{id}/users
          cors: true
          authorizer: ${self:custom.authorizer.main}
  list-users:
    handler: list-users.main
    events:
      - http:
          method: get
          path: users/list
          cors: true
          authorizer: ${self:custom.authorizer.main}
  user-signup:
    handler: user-signup.main
    events:
      - http:
          method: post
          path: register
          cors: true
  user-confirm:
    handler: user-confirm.main
    events:
      - http:
          method: post
          path: register/confirm
          cors: true
  user-signin:
    handler: user-signin.main
    events:
      - http:
          method: post
          path: login
          cors: true
  user-signout:
    handler: user-signout.main
    events:
      - http:
          method: post
          path: logout
          cors: true
          authorizer: ${self:custom.authorizer.main}
  user-get:
    handler: user-get.main
    events:
      - http:
          method: get
          path: users
          request:
            parameters:
              querystrings:
                AccessToken: true
          cors: true
          authorizer: ${self:custom.authorizer.default}
  user-modify-attributes:
    handler: user-modify-attributes.main
    events:
      - http:
          method: put
          path: users
          cors: true
          authorizer: ${self:custom.authorizer.default}